# Symptom Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv("../data/diseasedata1.csv")
df.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [3]:
df = df.sample(frac = 1) 
df

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
678         0          0                     0                    1   
2125        0          0                     0                    0   
2069        0          0                     0                    1   
2777        0          0                     0                    0   
3460        1          1                     0                    0   
...       ...        ...                   ...                  ...   
518         0          0                     0                    0   
930         0          0                     0                    0   
618         1          0                     0                    0   
1307        0          0                     0                    0   
2477        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
678           0       1           0             0        0                 0   
2125          0       0           0             0        0                 0   
2069          1       1           0             0        0                 0   
2777          0       0           0             0        0                 0   
3460          0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
518           0       0           0             0        0                 0   
930           0       0           0             0        1                 0   
618           0       0           0             0        0                 0   
1307          0       0           0             0        0                 0   
2477          0       1           1             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
678   ...           0         0             0                    0   
2125  ...           0         0             0                    0   
2069  ...           0         0             0                    0   
2777  ...           0         0             0                    0   
3460  ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
518   ...           0         0             0                    0   
930   ...           0         0             0                    0   
618   ...           0         0             0                    0   
1307  ...           0         0             0                    0   
2477  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
678                      0                   0        0                     0   
2125                     0                   0        0                     0   
2069                     0                   0        0                     0   
2777                     0                   0        0                     0   
3460                     0                   0        0                     0   
...                    ...                 ...      ...                   ...   
518                      0                   0        0                     0   
930                      0                   0        0                     0   
618                      0                   0        0                     0   
1307                     0                   0        0                     0   
2477                     0                   0        0                     0   

      yellow_crust_ooze       prognosis  
678                   0     Common Cold  
2125                  0       Diabetes   
2069                  0         Allergy  
2777                  0  Varicose veins  
3460                  0     Chicken pox  
...                 ...             ...  
518                   0   Hypertension   
930                   0        Migraine  


In [4]:
df=df.reset_index(drop=True)
df

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
0           0          0                     0                    1   
1           0          0                     0                    0   
2           0          0                     0                    1   
3           0          0                     0                    0   
4           1          1                     0                    0   
...       ...        ...                   ...                  ...   
4957        0          0                     0                    0   
4958        0          0                     0                    0   
4959        1          0                     0                    0   
4960        0          0                     0                    0   
4961        0          1                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
0             0       1           0             0        0                 0   
1             0       0           0             0        0                 0   
2             1       1           0             0        0                 0   
3             0       0           0             0        0                 0   
4             0       0           0             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
4957          0       0           0             0        0                 0   
4958          0       0           0             0        1                 0   
4959          0       0           0             0        0                 0   
4960          0       0           0             0        0                 0   
4961          0       1           1             0        0                 0   

      ...  blackheads  scurring  skin_peeling  silver_like_dusting  \
0     ...           0         0             0                    0   
1     ...           0         0             0                    0   
2     ...           0         0             0                    0   
3     ...           0         0             0                    0   
4     ...           0         0             0                    0   
...   ...         ...       ...           ...                  ...   
4957  ...           0         0             0                    0   
4958  ...           0         0             0                    0   
4959  ...           0         0             0                    0   
4960  ...           0         0             0                    0   
4961  ...           0         0             0                    0   

      small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                        0                   0        0                     0   
1                        0                   0        0                     0   
2                        0                   0        0                     0   
3                        0                   0        0                     0   
4                        0                   0        0                     0   
...                    ...                 ...      ...                   ...   
4957                     0                   0        0                     0   
4958                     0                   0        0                     0   
4959                     0                   0        0                     0   
4960                     0                   0        0                     0   
4961                     0                   0        0                     0   

      yellow_crust_ooze       prognosis  
0                     0     Common Cold  
1                     0       Diabetes   
2                     0         Allergy  
3                     0  Varicose veins  
4                     0     Chicken pox  
...                 ...             ...  
4957                  0   Hypertension   
4958                  0        Migraine  


In [5]:
df.dtypes

itching                  int64
skin_rash                int64
nodal_skin_eruptions     int64
continuous_sneezing      int64
shivering                int64
                         ...  
inflammatory_nails       int64
blister                  int64
red_sore_around_nose     int64
yellow_crust_ooze        int64
prognosis               object
Length: 133, dtype: object

In [6]:
df.describe()

itching    skin_rash  nodal_skin_eruptions  continuous_sneezing  \
count  4962.000000  4962.000000           4962.000000          4962.000000   
mean      0.138049     0.160016              0.021967             0.045143   
std       0.344986     0.366658              0.146590             0.207639   
min       0.000000     0.000000              0.000000             0.000000   
25%       0.000000     0.000000              0.000000             0.000000   
50%       0.000000     0.000000              0.000000             0.000000   
75%       0.000000     0.000000              0.000000             0.000000   
max       1.000000     1.000000              1.000000             1.000000   

         shivering       chills   joint_pain  stomach_pain      acidity  \
count  4962.000000  4962.000000  4962.000000   4962.000000  4962.000000   
mean      0.021967     0.162233     0.139057      0.045143     0.045143   
std       0.146590     0.368702     0.346041      0.207639     0.207639   
min       0.000000     0.000000     0.000000      0.000000     0.000000   
25%       0.000000     0.000000     0.000000      0.000000     0.000000   
50%       0.000000     0.000000     0.000000      0.000000     0.000000   
75%       0.000000     0.000000     0.000000      0.000000     0.000000   
max       1.000000     1.000000     1.000000      1.000000     1.000000   

       ulcers_on_tongue  ...  pus_filled_pimples   blackheads     scurring  \
count       4962.000000  ...         4962.000000  4962.000000  4962.000000   
mean           0.021967  ...            0.021967     0.021967     0.021967   
std            0.146590  ...            0.146590     0.146590     0.146590   
min            0.000000  ...            0.000000     0.000000     0.000000   
25%            0.000000  ...            0.000000     0.000000     0.000000   
50%            0.000000  ...            0.000000     0.000000     0.000000   
75%            0.000000  ...            0.000000     0.000000     0.000000   
max            1.000000  ...            1.000000     1.000000     1.000000   

       skin_peeling  silver_like_dusting  small_dents_in_nails  \
count   4962.000000          4962.000000           4962.000000   
mean       0.023378             0.023176              0.023176   
std        0.151115             0.150478              0.150478   
min        0.000000             0.000000              0.000000   
25%        0.000000             0.000000              0.000000   
50%        0.000000             0.000000              0.000000   
75%        0.000000             0.000000              0.000000   
max        1.000000             1.000000              1.000000   

       inflammatory_nails      blister  red_sore_around_nose  \
count         4962.000000  4962.000000           4962.000000   
mean             0.023176     0.023176              0.023378   
std              0.150478     0.150478              0.151115   
min              0.000000     0.000000              0.000000   
25%              0.000000     0.000000              0.000000   
50%              0.000000     0.000000              0.000000   
75%              0.000000     0.000000              0.000000   
max              1.000000     1.000000              1.000000   

       yellow_crust_ooze  
count        4962.000000  
mean            0.023176  
std             0.150478  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max             1.000000  

[8 rows x 132 columns]

In [7]:
df.prognosis=df.prognosis.astype(str)
df.prognosis.dtype

dtype('O')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4962 entries, 0 to 4961
Columns: 133 entries, itching to prognosis
dtypes: int64(132), object(1)
memory usage: 5.0+ MB


In [9]:
df.isnull().any()

itching                 False
skin_rash               False
nodal_skin_eruptions    False
continuous_sneezing     False
shivering               False
                        ...  
inflammatory_nails      False
blister                 False
red_sore_around_nose    False
yellow_crust_ooze       False
prognosis               False
Length: 133, dtype: bool

In [10]:
df.shape

(4962, 133)

In [11]:
diseases=df.prognosis.unique()
diseases, len(diseases)

(array(['Common Cold', 'Diabetes ', 'Allergy', 'Varicose veins',
        'Chicken pox', 'Hypoglycemia', 'AIDS', 'Osteoarthristis',
        'Paralysis (brain hemorrhage)', 'Typhoid', 'Malaria',
        'Gastroenteritis', 'Urinary tract infection', 'Hypertension ',
        'Bronchial Asthma', 'Pneumonia',
        '(vertigo) Paroymsal  Positional Vertigo', 'Impetigo', 'Migraine',
        'Hepatitis D', 'Arthritis', 'hepatitis A', 'Hepatitis C',
        'Hyperthyroidism', 'Jaundice', 'Chronic cholestasis',
        'Dimorphic hemmorhoids(piles)', 'Psoriasis',
        'Cervical spondylosis', 'Alcoholic hepatitis', 'Hepatitis E',
        'Peptic ulcer diseae', 'Fungal infection', 'Hepatitis B',
        'Heart attack', 'Dengue', 'Drug Reaction', 'GERD', 'Acne',
        'Hypothyroidism', 'Tuberculosis'], dtype=object),
 41)

In [12]:
df.groupby('prognosis').size()

prognosis
(vertigo) Paroymsal  Positional Vertigo    121
AIDS                                       121
Acne                                       121
Alcoholic hepatitis                        121
Allergy                                    121
Arthritis                                  121
Bronchial Asthma                           121
Cervical spondylosis                       121
Chicken pox                                121
Chronic cholestasis                        121
Common Cold                                121
Dengue                                     121
Diabetes                                   121
Dimorphic hemmorhoids(piles)               121
Drug Reaction                              121
Fungal infection                           122
GERD                                       121
Gastroenteritis                            121
Heart attack                               121
Hepatitis B                                121
Hepatitis C                                121
Hep

In [13]:
df.corr()

itching  skin_rash  nodal_skin_eruptions  \
itching               1.000000   0.319331              0.326653   
skin_rash             0.319331   1.000000              0.298366   
nodal_skin_eruptions  0.326653   0.298366              1.000000   
continuous_sneezing  -0.087017  -0.094901             -0.032586   
shivering            -0.059977  -0.065412             -0.022460   
...                        ...        ...                   ...   
small_dents_in_nails -0.061644   0.330991             -0.023085   
inflammatory_nails   -0.061644   0.330991             -0.023085   
blister              -0.061644   0.330991             -0.023085   
red_sore_around_nose -0.058051   0.332651             -0.023187   
yellow_crust_ooze    -0.061644   0.330991             -0.023085   

                      continuous_sneezing  shivering    chills  joint_pain  \
itching                         -0.087017  -0.059977 -0.176110   -0.160836   
skin_rash                       -0.094901  -0.065412 -0.029542    0.170927   
nodal_skin_eruptions            -0.032586  -0.022460 -0.065950   -0.060231   
continuous_sneezing              1.000000   0.609789  0.446711   -0.087385   
shivering                        0.609789   1.000000  0.295811   -0.060231   
...                                   ...        ...       ...         ...   
small_dents_in_nails            -0.033492  -0.023085 -0.067783    0.360042   
inflammatory_nails              -0.033492  -0.023085 -0.067783    0.360042   
blister                         -0.033492  -0.023085 -0.067783   -0.061904   
red_sore_around_nose            -0.033641  -0.023187 -0.068084   -0.062179   
yellow_crust_ooze               -0.033492  -0.023085 -0.067783   -0.061904   

                      stomach_pain   acidity  ulcers_on_tongue  ...  \
itching                   0.202823 -0.087017         -0.059977  ...   
skin_rash                 0.161921 -0.094901         -0.065412  ...   
nodal_skin_eruptions     -0.032586 -0.032586         -0.022460  ...   
continuous_sneezing      -0.047277 -0.047277         -0.032586  ...   
shivering                -0.032586 -0.032586         -0.022460  ...   
...                            ...       ...               ...  ...   
small_dents_in_nails     -0.033492 -0.033492         -0.023085  ...   
inflammatory_nails       -0.033492 -0.033492         -0.023085  ...   
blister                  -0.033492 -0.033492         -0.023085  ...   
red_sore_around_nose     -0.033641 -0.033641         -0.023187  ...   
yellow_crust_ooze        -0.033492 -0.033492         -0.023085  ...   

                      pus_filled_pimples  blackheads  scurring  skin_peeling  \
itching                        -0.059977   -0.059977 -0.059977     -0.058051   
skin_rash                       0.320868    0.320868  0.320868      0.332651   
nodal_skin_eruptions           -0.022460   -0.022460 -0.022460     -0.023187   
continuous_sneezing            -0.032586   -0.032586 -0.032586     -0.033641   
shivering                      -0.022460   -0.022460 -0.022460     -0.023187   
...                                  ...         ...       ...           ...   
small_dents_in_nails           -0.023085   -0.023085 -0.023085      0.942391   
inflammatory_nails             -0.023085   -0.023085 -0.023085      0.942391   
blister                        -0.023085   -0.023085 -0.023085     -0.023831   
red_sore_around_nose           -0.023187   -0.023187 -0.023187     -0.015110   
yellow_crust_ooze              -0.023085   -0.023085 -0.023085     -0.023831   

                      silver_like_dusting  small_dents_in_nails  \
itching                         -0.061644             -0.061644   
skin_rash                        0.330991              0.330991   
nodal_skin_eruptions            -0.023085             -0.023085   
continuous_sneezing             -0.033492             -0.033492   
shivering                       -0.023085             -0.023085   
...                                   ...                   ...  

In [14]:
X=df.drop(columns=['prognosis'])
X.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        0          0                     0                    1          0   
1        0          0                     0                    0          0   
2        0          0                     0                    1          1   
3        0          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       1           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       1           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   
2                   0           0         0             0   
3                   0           0         0             0   
4                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 132 columns]

In [15]:
Y=df['prognosis']
Y.head()

0       Common Cold
1         Diabetes 
2           Allergy
3    Varicose veins
4       Chicken pox
Name: prognosis, dtype: object

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [17]:
X_train.shape,X_test.shape

((3721, 132), (1241, 132))

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import tree
from sklearn import model_selection
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [19]:

def train_model(model):
    model.fit(X_train,Y_train)
    prediction=model.predict(X_test)
    score=accuracy_score(Y_test,prediction)
    print(confusion_matrix(Y_test,prediction,labels=diseases))
    print(classification_report(Y_test,prediction, labels=diseases))
    return score

In [20]:
model=[DecisionTreeClassifier(),SVC(),LogisticRegression(),GaussianNB(),KNeighborsClassifier(n_neighbors=21),RandomForestClassifier(n_estimators=101)]
score=[]
for i in model:
    x=train_model(i)
    score.append(x)
result=dict(zip(model,score))
result

[[29  0  0 ...  0  0  0]
 [ 0 41  0 ...  0  0  0]
 [ 0  0 42 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0 33]]
                                         precision    recall  f1-score   support

                            Common Cold       1.00      1.00      1.00        29
                              Diabetes        1.00      1.00      1.00        41
                                Allergy       1.00      1.00      1.00        42
                         Varicose veins       1.00      1.00      1.00        32
                            Chicken pox       1.00      1.00      1.00        32
                           Hypoglycemia       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        31
                        Osteoarthristis       1.00      1.00      1.00        27
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        36
                                T

[[29  0  0 ...  0  0  0]
 [ 0 41  0 ...  0  0  0]
 [ 0  0 42 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0 33]]
                                         precision    recall  f1-score   support

                            Common Cold       1.00      1.00      1.00        29
                              Diabetes        1.00      1.00      1.00        41
                                Allergy       1.00      1.00      1.00        42
                         Varicose veins       1.00      1.00      1.00        32
                            Chicken pox       1.00      1.00      1.00        32
                           Hypoglycemia       1.00      1.00      1.00        33
                                   AIDS       1.00      1.00      1.00        31
                        Osteoarthristis       1.00      1.00      1.00        27
           Paralysis (brain hemorrhage)       1.00      1.00      1.00        36
                                T

{DecisionTreeClassifier(): 1.0,
 SVC(): 1.0,
 LogisticRegression(): 1.0,
 GaussianNB(): 1.0,
 KNeighborsClassifier(n_neighbors=21): 1.0,
 RandomForestClassifier(n_estimators=101): 1.0}

In [21]:
df.columns

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [22]:
a=np.zeros(132)
a[3]=1
a[28]=1
a[27]=1
for i in range(len(model)):
    print(model[i],model[i].predict([a]))


DecisionTreeClassifier() ['Allergy']
SVC() ['Heart attack']
LogisticRegression() ['Heart attack']
GaussianNB() ['Heart attack']
KNeighborsClassifier(n_neighbors=21) ['Heart attack']
RandomForestClassifier(n_estimators=101) ['Heart attack']


In [23]:
b=np.zeros(132)
b[0]=1
b[1]=1
b[2]=1
for i in range(len(model)):
    print(model[i],model[i].predict([b]))

DecisionTreeClassifier() ['Fungal infection']
SVC() ['Fungal infection']
LogisticRegression() ['Fungal infection']
GaussianNB() ['Fungal infection']
KNeighborsClassifier(n_neighbors=21) ['Fungal infection']
RandomForestClassifier(n_estimators=101) ['Fungal infection']
